### ISSUE TITLE
Conditional content appear for a little amount of time then dissapear when page refresh

### ISSUE THREAD

**Issue by ilyes24** [scullyio/scully#1274]
### Description
The content of a **refreshed** web page is all loaded for the first time (even sections that are related with an `*ng-If`), then those sections are removed after small amount of time
#### 🔬 Minimal Reproduction
for example `cookies modal` in the home page
https://client.stagging.izeelogo.com
#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 11.1.4
Node: 14.15.5
OS: win32 x64
Angular:
...
Ivy Workspace:
Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1101.4 (cli-only)
@angular-devkit/core         11.1.4 (cli-only)
@angular-devkit/schematics   11.1.4 (cli-only)
@schematics/angular          11.1.4 (cli-only)
@schematics/update           0.1101.4 (cli-only)
</code></pre>

**Scully Version:**

<pre><code>
"@scullyio/init": "^1.0.1",
"@scullyio/ng-lib": "^1.1.0",
"@scullyio/scully": "^1.0.0",
</code></pre>

**Comment by ilyes24** [comment]
@SanderElias  is there a bad implementation by my side ?

**Comment by SanderElias** [comment]
@ilyes24 I do suspect your static content isn't the same as the content you are loading in your app. 
You can bring those in sync by using transferstate service, or by using `isScullyRunning()` during generation.
Scully does see every page of your site as a user on its very first visit to your site. So that is what gets rendered. 
If you need to deviate from that, you need to use one of the available options.

**Comment by SanderElias** [comment]
Closing as there is no actionable issue left. Feel free to keep discussing in this thread.
We can reopen, or start a new issue if needed.
