### ISSUE TITLE
Scully init ng-add schematic silently fails when there is invalid json in `angular.json`

### ISSUE THREAD

**Issue by SanderElias** [scullyio/scully#1299]
### Description
As an example, when there is a trailing comma in one of the array's in `angular.json` the CLI will just work.
However, running `ng add @scullyio/init` will silently fail. It will exit without an error before its done.

**Comment by SanderElias** [comment]
When you have this issue. I did explain how to do a [manual installation here](https://github.com/scullyio/scully/issues/1297#issuecomment-805795681)

**Comment by BenLune** [comment]
Thanks @SanderElias ,
I had the same kind of problem, but with an error, and not while the installation process. When running npm run scully, I had an error telling that Scully didn't find my project in the angular.json, but it was in. Thanks to this issue, I understood that the reason was a guilty comma in the angular.json file, then the JSON was invalid for Scully. After removing the comma, it was ok...
It's quite important to check if the angular.json file is valid when error or strange behaviour occurs.

**Comment by SanderElias** [comment]
Related to #1402 
I'm going to close this one, so we can concentrate discussion over there.
