### ISSUE TITLE
Install error on apple m1 silicon

### ISSUE THREAD

**Issue by davidecampello** [scullyio/scully#1383]
## 🐞 Bug report
Installing scully in a mac with silicon produce this error
The chromium binary is not available for arm64

### Description
I think puppeteer should be upgraded to latest version if possible
https://github.com/puppeteer/puppeteer/issues/6622

#### 💻Your Environment
**Angular Version:**

<pre><code>
Angular CLI: 12.0.1
Node: 16.2.0
Package Manager: npm 7.13.0
OS: darwin arm64

</code></pre>

**Scully Version:**

<pre><code>
1.1.4

</code></pre>

**Comment by SanderElias** [comment]
Angular and NPM 7 are not good friends. The culprit might be there?
If you manually install `npm i puppeteer` it might just work.  As long as puppeteer doesn't have breaking API changes, it should work.
Can you let us know?

**Comment by a45b** [comment]
@aaronfrost 

The chromium binary is not available for arm64:
If you are on Ubuntu, you can install with:

 apt-get install chromium-browser
 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@5.5.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@5.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by a45b** [comment]
@SanderElias - I tried `npm i puppeteer` - puppeteer seems installed.
But after that should I do `ng add @scullyio/init`? (I did and result in the same error)
I also did `npm install @scullyio/init` - which result in the error again (but even it's successfully how to run :install)
I'm not using Nx

Can we replace puppeteer with playwright? 
playwright API is similar, so it should be much issue - I guess

**Comment by niklaas** [comment]
Best solution would be to update the dependency to `puppeteer` to the most recent version because this has been fixed (see https://github.com/puppeteer/puppeteer/pull/6495) and the current version

https://github.com/scullyio/scully/blob/aa9fd74f3e852d2b584ea84a293865b0d4fa1ebe/package.json#L103

looks rather outdated (as of this writing the most recent version is `v10.1.0`).

While this project still depends on the old version, you can force to use a newer version of puppeteer in your project by adding the following lines to your `package.json` file

```
{
  ...
  scripts: {
    ...
    "preinstall": "npx npm-force-resolutions"
  },
   ...
  "resolutions": {
    "puppeteer": "^10.1.0"
  }
  ...
}
```

and run `npm i` afterwards.

**Comment by davidecampello** [comment]
Hello! Thank you for your answers!
I tried running npm i puppeteer and with @niklaas solution but I alwais have the error 
The chromium binary is not available for arm64.
I don't know why...

**Comment by SanderElias** [comment]
@davidecampello In some cases `npm i puppeteer` does not install chrome, and you need to manually install one.
the steps are described in the puppeteer troubleshooting documentation, which we refer to in the error-message.

Also, there seems to be helpful info over here: https://github.com/puppeteer/puppeteer/issues/6622

**Comment by davidecampello** [comment]
thanks @SanderElias, I'll try later

**Comment by makitsune** [comment]
@niklaas Thanks so much for your answer. I didn't know `resolutions` was a thing until today! 

Really though, @scullyio/scully should update puppeteer from 5 (released in Nov 16, 2020) to 10.

**Comment by Jefiozie** [comment]
Hi, in the latest version of Scully we have made some significant changes. We abstracted the puppeteer renderer to be a plugin and added a playwright render plugin. With this change, we hope to support a bigger variety of browsers and hope that this problem is resolved. Within a week or so we will release a new version, if somebody would verify that this problem then is resolved that would be great,

thanks

**Comment by Splaktar** [comment]
I don't see this error anymore with
```json
    "@scullyio/init": "~2.0.5",
    "@scullyio/ng-lib": "~2.0.2",
    "@scullyio/scully": "^2.0.3",
```
But I am getting
```ts
 error TS2739: Type 'Observable<unknown>' is missing the following properties from type 'Observable<ScullyRoute>': _isScalar, _trySubscribe, _subscribe

34     this.article = this.scullyRoutesService.getCurrent().pipe(
```
Is there a change log or other record of the breaking changes in v2?

**Comment by SanderElias** [comment]
@Splaktar We are working on the changelog. Due to "technical difficulties", we seem to have lost a significant part there.
But there was no recent change in that area of the code, so I don't think that should break. This is the code, and it seems untouched for 2 years:

```typescript
  getCurrent(): Observable<ScullyRoute> {
     /** implementation details here */
  }
```
I checked the implementation and all the types in there are correct too.
So, I'm not sure if/how your issue is related.

**Comment by Splaktar** [comment]
Thank you for looking into this Sander. I don't think that the code changed. It seems like a dependency changed, I.e. RxJs v7

**Comment by SanderElias** [comment]
I'm testing with rx7, but I have coded the libs so that they should work with both. What version of rx are you using?

**Comment by Splaktar** [comment]
@SanderElias `"rxjs": "^6.6.7",`, but I'm seeing this in `npm ls rxjs`
```
├─┬ @scullyio/ng-lib@2.0.2
│ └── rxjs@7.4.0 
├─┬ UNMET PEER DEPENDENCY @scullyio/scully@2.0.3
│ └── rxjs@7.4.0 
```

**Comment by Splaktar** [comment]
Just as a follow up on this, I had to update to RxJS v7 to get this working. It doesn't appear that v2 supports RxJS v6.

Additionally, I don't think that there are any more m1 issues in the latest Scully v2.

**Comment by SanderElias** [comment]
I'm closing this issue now, as it is resolved. We recently verified once more that we can run/build/test Scully in full on an M1 machine.
