### ISSUE TITLE
How does one configure the file structure for the static files?

### ISSUE THREAD

**Issue by tenoriojuann** [scullyio/scully#1408]
Hi,

I have a requirement to be able to save all the static HTML next to each other. This means that rather than having folders for every route and then having an index.html I would need to get rid of the folders and name the static HTML the same as the route.

From this:
```
dist
|__blog
    |__index.html
```
To:
```
dist
|__blog.html
````

**Comment by SanderElias** [comment]
@tenoriojuann We don't provide a possibility for this out of the box. Most servers are not equipped to handle this way of distribution a website, and you are going to get edge-cases.
(full disclosure, this was how I did set it up in the first version, way before release. I did step away from it because it causes more problems than it was worth)
If you really want to do this anyway, you can clone the `writeToFs` plugin, and tell Scully to use yours instead of the one we provide.

BTW, you can only use inlined transferState in this scenario, unless you rewire Scully's ngLib too.

I'm going to close this issue, as we will not provide this out of the box.
If you have questions on how to proceed on your own, feel free to keep discussing in here.
