### ISSUE TITLE
Exclude some routes from static site generation 

### ISSUE THREAD

**Issue by xmlking** [scullyio/scully#154]
# 🧩 Feature request
Exclude some routes from static site generation(SSG) 

### Description
I have OpenID Connect setup with google and I am using route `/home/callback`  for google to redirect with token.  I want to prevent this route from being generated statically as it is generating breaking code.

generated : `home/callback/index.html`  has `http://localhost:1864/home/callback`

```html
<p id="errorDescription">
The redirect URI in the request, http://localhost:1864/home/callback, 
does not match the ones authorized for the OAuth client. 
To update the authorized redirect URIs, visit: 
https://console.developers.google.com/apis/credentials/oauthclient/1111111111111-sgsgsgsgsgsgsg.apps.googleusercontent.com?project=5555555555555
</p>
```

### Describe the solution you'd like
I should be able to provide a list of routes that should be excluded from (SSG), may be in `scully.config.js`

### Describe alternatives you've considered
As a workaround,  I am manually deleting `dist/scully/apps/webapp/home/callback/index.html` before uploading to the server.
This works as expected: https://ngx-starter-kit.firebaseapp.com/home

Source : https://github.com/xmlking/yeti

**Comment by chrisguttandin** [comment]
I remember that I talked about a similar feature with @MarkPieszak when we had a chat about the new prerender schematics of Angular Universal. I would love to add a similar feature to angular-prerender as well. I wonder if there is a way to make this work across all three prerendering options.

Back then Mark and I had the idea to add a key to the [data](https://angular.io/api/router/Route#data) property that each route can have. Since we all use the guess-parser it should be possible to read that when parsing the routes.

```typescript
const routes = [
    {
        component: MyComponent,
        data: { prerender: false },
        path: '/myroute'
    }
];
```

Would something like this work for Scully as well?

@MarkPieszak did you implement that feature in the end?

**Comment by xmlking** [comment]
Route data might be an appropriate place to set this flag, so that other tools also leverage this information. 
I see  @mgechev also using `preload` flag like this in https://github.com/mgechev/ngx-quicklink

**Comment by chrisguttandin** [comment]
`ngx-quicklink` has the adventage that it doesn't have to parse the routes statically. However I think it is possible to extend `guess-parser` to read the `data` property. I already did a quick check with a quick-and-dirty patch and (at least for my test cases) it worked fine.

In case we have consensus on using a special `prerender` property I'm happy to provide a pull request for `guess-parser`.

Another option could be to use the HTTP response code. If a request results in a 4xx or 5xx the route could be excluded. But I guess that's difficult to implement in Scully.

Yet another option could be to listen for redirects and if a page has a redirect it could be excluded.

But I still think allowing the user to explicitly exclude routes is much better since the other two options might sound elegant but surely have edge cases for which they don't work so well.

**Comment by SanderElias** [comment]
I will create a sample voidPlugin that takes out routes from the list.
