### ISSUE TITLE
After running npx scully, I got the same html content

### ISSUE THREAD

**Issue by jiangyh1024** [scullyio/scully#1576]
<img width="828" alt="image" src="https://user-images.githubusercontent.com/34930870/163353413-082c5e7c-b938-4502-b21c-5470e1f792de.png">

<img width="269" alt="image" src="https://user-images.githubusercontent.com/34930870/163353504-9ce28518-bdc5-4eb2-8dd1-2650f1b0cd72.png">
<img width="664" alt="image" src="https://user-images.githubusercontent.com/34930870/163353544-87d55dec-9e16-4318-8d56-fc60215138b6.png">

but in about.html
I got
<img width="739" alt="image" src="https://user-images.githubusercontent.com/34930870/163353660-2680f7f0-6318-4399-83d8-abbce90239d5.png">

**Comment by jiangyh1024** [comment]
<img width="712" alt="image" src="https://user-images.githubusercontent.com/34930870/163353829-7f60a2dd-9152-4f5b-82d4-2796685ae06c.png">

this is the config file

**Comment by jiangyh1024** [comment]
content in home.html and about.html is the same....

**Comment by jiangyh1024** [comment]
It seems that this is caused by hash routing. I am using hash routing instead of h5 routing....

Don't know whether this can be regarded as a bug or not ..

**Comment by SanderElias** [comment]
Scully doesn't support hash routing. The reason is that 90% of the servers can't handle this.
We can write those files to disk, but most of the servers will have serious trouble serving those files. 
(mostly, because everything after `#` is considered client-side, and the servers just truncate those)
I don't think this is something that can be solved.

**Comment by jiangyh1024** [comment]
Thx, I'm going to use H5 routing
