### ISSUE TITLE
scully cannot generate right html if route guard is applied

### ISSUE THREAD

**Issue by jiangyh1024** [scullyio/scully#1577]
<img width="558" alt="image" src="https://user-images.githubusercontent.com/34930870/163502782-d79a50a6-5ed9-4311-8b21-5cf12b3fd7ba.png">

after removing the guards as above, scully works as expected. 

I wanna know why and how to solve the problem ?

**Comment by SanderElias** [comment]
For SSG to work, Scully has to visit every page as a new user hitting that page for the first time.
So, that is what it is doing by design.
If you want to change something so it works slightly differently for your use-case, you can use `isScullyRunning()` in your code, and work around whatever you want.

Be aware, that if your app requires a log-in before displaying any content, and you are using `isScullyRunning()` to skip checks, all the information will become publicly available by default.

Most apps that need a login are not compatible with Jamstack/SSG.
