### ISSUE TITLE
[BUG] npm run scully, <scully-content> not found when inside ngIf

### ISSUE THREAD

**Issue by jasper-jool** [scullyio/scully#226]
Running the scully command gives an error (missing "<scully-content>" or "httpClientModule") when the scully-content tag is inside an element with an `*ngIf`.

For example:

```
<button (click)="showDetails()">Show Details</button>
```

```
<ng-container *ngIf="details">
   <scully-content></scully-content>
</ng-container>
```
I can imagine people hiding the scully content at first and showing it after some user interaction.

**Comment by SanderElias** [comment]
@jasper-jool This is not possible with a static page. If you want to hide the Scully-content you need to do it with CSS, or some class. Being a static site means the page is active _before_ JS starts up. 
The `<scully-content>` tag needs to be on the page when it is rendered. 

@Villanuevand Perhaps we should mention this is the documentation?
I'm going to close this issue because there is nothing we can act upon.
