### ISSUE TITLE
How to use in combination with baseHref on external url?

### ISSUE THREAD

**Issue by Enngage** [scullyio/scully#540]
### Description

Hey guys,

I was testing scully and encountered an issue that when you define **baseHref** in **angular.json** to an external URL such as:

```typescript
 "configurations": {
            "production": {
              "outputPath": "dist/prod",
              "baseHref": "https://cdn.com/app/",
              "optimization": true,
              "outputHashing": "all",
              ...
```
the generated html files are pretty much empty, which makes sense because the files are not yet uploaded to external source and requests to files fail with 404. The external source in this case is CDN where the final build is pushed.

Is there a way to let scully use "local" base href to generate html files, but use external baseHref in final output build so that it can then be deployed to external destination?

**Comment by dyingangel666** [comment]
Same with all custom baseHref's which are different than the default "/". It a baseHref is set, the prerendered html files are empty within the <app-root></app-root> part. Same things happen when you use the angular i18n tools and build your project with the --localize flag, then angular automatically sets the baseHref to "/de/" or "/en/" automatically because angular builds a separate project for each language into a subfolder... 

I thing this is definitely a bug, because setting the baseHref is a default feature of angular but scully is not yet using the baseHref

**Comment by SanderElias** [comment]
@dyingangel666 Setting the base-href is a feature of Angular-CLI. Angular itself does actually nothing. 
I'm currently working on a plugin that allows you to rewrite the base-href. That will be configurable, and even different for routes. Ihope this will be available this week.
