### ISSUE TITLE
Does Scully support angular web components?

### ISSUE THREAD

**Issue by alexbjorlig** [scullyio/scully#586]
### Description

I can't find in the docs, if Scully will support angular web components. 

Let's say that I have created an Angular web component called library-a.

This web component is used both in a Wordpress site, but also in another "normal" angular SPA. If I use Scully on this "normal" SPA, will the page with the web component static render?

I new to this static rendering, and trying to figure out what is possible with our current setup. Thanks for a great project.

**Comment by SanderElias** [comment]
Everything that is in the light-dom will be rendered by Scully. 
This means it depends on how you did build your components. Also, it is depending on how/when you load your Elements code, and how those elements appear on the page.
So, it's hard to tell, or document, because there are many unknowns. We have a sample that utilizes some web-components on our roadmap, but that might take a while before it materializes.

I'm closing this for now, because there is no additional action we can take for this. (the sample and the docs for it are already in-flight)

**Comment by alexbjorlig** [comment]
Thanks for taking your time to answer - we will go ahead and try to build a small POC and determine if Scully is a good match 🤓  Sounds awesome with the upcoming examples - you are doing a great job 🙌🏾
