### ISSUE TITLE
404.html page not served 

### ISSUE THREAD

**Issue by etavener** [scullyio/scully#641]
### Description
I created a custom 404 page in my application. I used this postRendered Plugin:
https://www.npmjs.com/package/@gammastream/scully-plugin-http404

However, when serving the app via Scully I see an embedded 404 page set in express instead of the actual 404 in the static files.

This might not be an issue when deploying and serving static files created as the 404 has been updated, but I think it would be good to see the same behaviour when serving via Scully as when it is finally deployed.

#### 🔬 Minimal Reproduction
Given I have updated the `dist/static/404.html` page (in this case via a PostRendered plugin)
When I serve the site via `npm run scully:serve`
And I visit a non-existent page `http://localhost:1668/page-does-not-exist` 
I expect to see the updated 404.html from `dist/static/404.html`

I currently see an un-styled / default HTML response embedded in the express serve.

#### 💻Your Environment

**Angular Version:**
<pre><code>
9.1.9
</code></pre>

**Scully Version:**
<pre><code>
0.0.95
</code></pre>

**Comment by msacket** [comment]
Hi @etavener, Plugin developer here.  The plugin is designed to specifically to meet the requirements for Firebase hosting.  I agree, it would be nice if it worked the same way with Scully serve, but given that sites could be deployed on any number of platforms, I think it's outside the scope of Scully... unless it could be supported in a generic way.

**Comment by SanderElias** [comment]
@etavener, This behavior is there by design. The Scully server is a development tool, and will inform you the page is _not_ rendered by your angular site by default, and you should take care of this in your production environment.
When we don't handle it this way, people might run int unpleasant surprises during deployment. 
I'm even considering to error out in this case, instead of rendering an empty page.
