### ISSUE TITLE
Never output "<pre>Cannot GET ____</pre>"

### ISSUE THREAD

**Issue by kylecordes** [scullyio/scully#649]
### Description

There is a failure modes in which Scully renders out one or more pages without their actual content, but instead something like:

<pre>Cannot GET /urlhere</pre>

#### 🔬 Minimal Reproduction

So far I don't know how to reproduce this, or how to make it stop.

#### 💻Your Environment

Details of the environment don’t matter.

## 🔥 Exception or Error

There is no error, rather just this output and the appearance of success. That is the problem. Scully appears to succeed but produces wrong output.

Please change it to **fail** if it cannot get what it needs to render pages, rather than produce output which may then be published by a CI pipeline yet is obviously incorrect.

**Comment by aaronfrost** [comment]
Find the code path that prints this error and at least give a more intelligible error, and try to get this error into the existing retry-rerender loop.

**Comment by SanderElias** [comment]
The pr #640 I address this issue. By default, now the `scully.rotues.json` is used as the source for the available routes.
Also, a more descriptive error is in place of the `Cannot GET /urlhere`, in case this happens somehow, and it has hints on how to solve the issue.
I'm closing this for now, but feel free to request a reopening if somehow this is still not enough.

**Comment by kylecordes** [comment]
In the PR it looks like, depending on how things are (mis)configured in an app, Scully could still succeed yet output pages that contain this (better) message. Which could then be published, perhaps even to a live customer-facing site, automatically depending on one’s CI configuration.

I think this is still problematic. Of course it is possible to work on at the application level, which I plan to do: grep for any of this text in the output and fail the build before getting to a deployment step (!).

**Comment by SanderElias** [comment]
@kylecordes THe pr allows for different solutions for the issue. There are different scenarios possible.
1. de default way, (new) uses the same info that is in scully.routes, and gives an error if the URL is unknown.
2. the 'old' way, still there because some people depend on this. uses the unhandled routes, and if its not there, it errors.
3. index, with return the index.html for every 404, you can use this if there are unknown/undiscovable routes in the app.
4. 404, results the 404.html for every 404, same as above, except uses a different file
5. none. scully leaves it to express to handle the page, this is for custom applications only.
If you need yet another scenario, please let me know, and I can probably integrate it.
