### ISSUE TITLE
Question: Product Lists

### ISSUE THREAD

**Issue by Marcusg62** [scullyio/scully#78]
Hi, I heard about Scully from Fireship and am really impressed. My team and I have battled with Angular Universal for 6 months now so this was much needed. We're ready to start converting my angular apps now! 
Though, I do have a question. There are some pages that display products based off data from [Firestore](https://firebase.google.com/docs/firestore)- a database.  

With scully, will this content to be fetched and rendered to the static pages? Would there be a difference if it is fetched in the constructor vs ngoninit? What are considerations here?

Since we deal with product lists (which for us change infrequently) we would need to build for scully and deploy nightly (or maybe even when DB changes). Any templates for cloud functions to do this?

Thanks guys!

**Comment by SanderElias** [comment]
@aaronfrost Can you take this one?

**Comment by SanderElias** [comment]
@Marcusg62 I know of at least 2 firebase plugins that are not yet published.
To answer your question.
Yes, the content is rendered to static pages. There is (from Scully standpoint) no difference in how this is fetched. 
However, we are going (pretty soon) a transfer state option, that makes it possible to load the data from the static pages instead of using firebase. That means, that once you have generated the pages, you don't need to connect to firebase at all anymore. 
You need to set up your environment to do this generation. That can be nightly, or, when you are using firebase, on updates if you like. 

I'm going to close your question as being answered, but I'm more than happy to reopen it  if you want me to

**Comment by khalithartmann** [comment]
Hello @SanderElias  where can I find the firebase plugins for Scully? Are they published yet? And do you know what the status is on the "transfer state option"?

**Comment by SanderElias** [comment]
@khalithartmann The transferState is fully implemented. I think a couple of days after my previous remark in this thread.

As far as I know. none did publish a firebase plugin (they are still in use tho)
Perhaps @jorgeucano knows a published firebase-plugin?
