### ISSUE TITLE
New Markdown Parser

### ISSUE THREAD

**Issue by cenguidanos** [scullyio/scully#802]
### Description

I see the limitations of marked markdown library and the limitations with plugins

### Describe the solution you'd like

This can be useful for scully? 

https://www.npmjs.com/package/node-markdown-parser

**Comment by SanderElias** [comment]
@cenguidanos Can you explain what the limitations you run into are? 
If you prefer another MD processor you can simply replace the plugin with one that uses the version you like.
We did choose `marked` because its a proven, well-established library with over 4.5 million downloads a week.
The library you are proposing is really new and has no proven track record yet. While it does look good I don't see a compelling reason to switch to this as the default MarkDown renderer just yet.
But nothing is keeping you from using it in Scully right now, by replacing the MD plugin with one of your own.

**Comment by cenguidanos** [comment]
ok, @SanderElias , thanks for the response
