### ISSUE TITLE
Documentation of --pjFirst Flag

### ISSUE THREAD

**Issue by brendanalexdr** [scullyio/scully#816]
When building with scully in the context of a monorepo, the following message alerts me to the suggested use of the "pjFirst" flag.  
```
 Config file ".\scully.my-project.config.ts" not found, only rendering routes without parameters
    The config file should have a name that is formated as:
       scully.<projectName>.config.ts
    where <projectName> is the name of the project as defined in the 'angular.json' file
    When you are in a mixed mono-repo you might need to use the --pjFirst flag
```
To get scully to work in a nx monorepo, I need to set the Default project angular.json config to the project I want scully to operate on.  I am assuming the --pjFirst flag has something do with executing scully on a particular project in a monorepo, but am having no luck understanding it.  The docs related to [Command Line Options](https://scully.io/docs/learn/command-line-options/) don't mentioned the --pjFirst flag.

**Comment by SanderElias** [comment]
@brendanalexdr the `--pjFirst` is a specialty flag that is only needed in repo's where there is _no_ Angular project. It looks for `package.json` instead of `angular.json` (@GuzmanPI can you add this to the docs?)
What you need is to use the `--project <yourPrrojectNameHere>` flag. You don't need to set a default in your angular.json. That is an optional step.
But I'll update the warning so it includes the '--project' flag

**Comment by GuzmanPI** [comment]
Sure! I can work on this

**Comment by brendanalexdr** [comment]
Many thanks for your help and clarification on this.  You guys really rock!
