### ISSUE TITLE
scrollIntoView - allow a way to position the fragments at the top not just centrally

### ISSUE THREAD

**Issue by etavener** [scullyio/scully#908]
### Description
When the URL has a fragment, Scully uses `scrollIntoView()` which is fine, but I would like to position this to be placed at the top instead of centered.

#### 🔬 Minimal Reproduction
This can also be seen on the Scully docs themselves:

Going directly to https://scully.io/docs/learn/core-features/idle-monitor-service/#adding-custom-mechanisms positions the element centrally. But if you use the menu on the right to navigate to the same element on the page it appears at the top.

#### 💻Your Environment

**Angular Version:**

<pre><code>

</code></pre>

**Scully Version:**

<pre><code>

</code></pre>

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by SanderElias** [comment]
@etavener The docs are currently scrolling to top. and not to center.
If there is not enough content below the tag your navigating, it can't scroll to the top, as it can't scroll behind page-end.
For example see [proxyconfig](https://scully.io/docs/learn/config/#proxyconfig-string) and [handle404](https://scully.io/docs/learn/config/#handle404-string)
The last one doesn't scroll to the top, because its close to the end of the page. The first one does, as there is enough content below the anchor.

I would prefer if we could come up with a way to have it scroll behind the page-end in those cases. 
We would love to get some ideas on how to handle that.

**Comment by etavener** [comment]
I've just looked at the scull docs again and the fragments aren't working there anymore.

See https://scully.io/docs/learn/config/#handled-routes it doesn't scroll to the element.

**Comment by etavener** [comment]
The docs seem to be scrolling to the top now. Was something updated?

**Comment by SanderElias** [comment]
@etavener Not something that has any relation with this. 
We do update the docs automatically if we merge into main. You might have been there during such an update.
