### ISSUE TITLE
Docs links broken on plugins page

### ISSUE THREAD

**Issue by asotog** [scullyio/scully#944]
### Description

Some docs pages links are broken

### What's the affected URL?\*\*

https://scully.io/docs/Reference/plugins/overview/

### Reproduction Steps\*\*

Click on `create the plugin function` link

### Expected vs Actual Behavior\*\*

Expected: go to specific page
Actual: is going to home page always

## 📷Screenshot

![image](https://user-images.githubusercontent.com/813023/93940971-b8ba8600-fcea-11ea-9a13-77024c0c2766.png)

**Comment by SanderElias** [comment]
Thanks for reporting this. 
We didn't catch this, because our test was checking if the URL's where working. As we did see the 404 page as a proper result, this didn't work for those links.
I updated the test to actually check for the route to exist now.
By doing this I found quite a couple of broken links!
Fixed now.

**Comment by asotog** [comment]
dank u... awesome
